[package]
name = "metal_l"
version = "0.1.0"
authors = ["yunfengzhang.zyf <yunfengzhang.zyf@alibaba-inc.com>"]
edition = "2018"
# 使用`cargo build`编译时需要的配置
[profile.dev]
panic = "abort" # 禁用panic时栈展开

# 使用`cargo build --release`编译时需要的配置
[profile.release]
panic = "abort" # 禁用panic时栈展开
[dependencies]
